import {
  Bike,
  Binoculars,
  Building2,
  Camera,
  Clapperboard,
  Coffee,
  Dices,
  Drama,
  Gamepad2,
  Image,
  Kayak,
  MicVocal,
  Music,
  Sailboat,
  ShoppingBag,
  Sparkles,
  TentTree,
  Utensils,
  Volleyball,
  WavesLadder,
  Wine,
} from 'lucide-react'
import {
  Baseball,
  Basketball,
  Boot,
  Bowling,
  BoxingGlove,
  Cloche,
  Column,
  DeskGlobe,
  DiscoBall,
  Drinks,
  Lotus,
  PingPong,
  Snorkel,
  SoccerBall,
  Surfboard,
  TargetArrow,
  TennisBall,
  TreeMountain,
  Walker,
} from './interestGlyphs'

const ICONS = {
  Arquitectura: Building2,
  Arte: Image,
  Básquet: Basketball,
  Béisbol: Baseball,
  Bowling,
  Boxeo: BoxingGlove,
  Buceo: Snorkel,
  Café: Coffee,
  Caminata: Walker,
  Camping: TentTree,
  Canotaje: Kayak,
  Canto: MicVocal,
  Ciclismo: Bike,
  Cine: Clapperboard,
  Cocina: Utensils,
  Comedia: Drama,
  Compras: ShoppingBag,
  'Cultura local': Binoculars,
  Fotografía: Camera,
  Fútbol: SoccerBall,
  Gastronomía: Cloche,
  Historia: DeskGlobe,
  'Juegos de mesa': Dices,
  Meditación: Lotus,
  Museos: Column,
  'Música en vivo': Music,
  Música: Music, // nombre viejo, por si quedó guardado así
  Natación: WavesLadder,
  Naturaleza: TreeMountain,
  Senderismo: Boot,
  Surf: Surfboard,
  Tenis: TennisBall,
  'Tenis de mesa': PingPong,
  'Tiro con arco': TargetArrow,
  Tragos: Drinks,
  Vela: Sailboat,
  'Vida nocturna': DiscoBall,
  Videojuegos: Gamepad2,
  Vinos: Wine,
  Vóley: Volleyball,
  Yoga: Lotus,
}

/** Ícono de cada interés (si llega uno desconocido desde el back, usa uno genérico). */
export function getInterestIcon(name) {
  return ICONS[name] ?? Sparkles
}
