import { useState } from 'react'
import { categories, experiences, sessions, reviews } from '../data/mockData'

function Money({ value }) {
  return <>{value.toLocaleString('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 })}</>
}

function Home({ filtered, category, setCategory, onSelect, onAuth }) {
  return <main>
    <section className="hero"><div className="hero-copy"><div className="intro-tag">✦ EXPERIENCIAS CURADAS PARA VOS</div><h1>Tu próximo<br /><em>plan empieza acá.</em></h1><p>Descubrí experiencias con personas copadas, elegí una sesión y reservá tu lugar para hacer algo distinto.</p><div className="hero-actions"><button className="primary-button" onClick={() => document.getElementById('experiences').scrollIntoView()}>Explorar experiencias <span>→</span></button><button className="text-button" onClick={onAuth}>Crear una cuenta</button></div></div><div className="hero-stamp"><span>PLAN</span><strong>Hacé algo<br />que te haga bien.</strong><small>Buenos Aires · 2025</small></div></section>
    <section className="section category-section"><div className="section-heading"><div><p className="eyebrow">EXPLORÁ POR CATEGORÍA</p><h2>¿Qué plan pinta?</h2></div><span className="result-count">{filtered.length} experiencias</span></div><div className="category-list">{categories.map((item) => <button className={`category-pill ${category === item ? 'selected' : ''}`} key={item} onClick={() => setCategory(item)}>{item === 'Todas' ? '✦' : item === 'Gastronomía' ? '🍴' : item === 'Arte & salidas' ? '🎨' : item === 'Escapadas' ? '🌿' : item === 'Música' ? '♫' : '✧'} <span>{item}</span></button>)}</div></section>
    <section className="section experiences-section" id="experiences"><div className="section-heading"><div><p className="eyebrow">PLANES DESTACADOS</p><h2>Elegí tu próxima experiencia</h2></div><button className="filter-button">☷ Filtros</button></div><div className="experience-grid">{filtered.map((item) => <ExperienceCard key={item.id} item={item} onSelect={onSelect} />)}</div>{!filtered.length && <Empty title="No encontramos ese plan" text="Probá con otra búsqueda o categoría." />}</section>
  </main>
}

function ExperienceCard({ item, onSelect }) {
  return <article className="experience-card" onClick={() => onSelect(item)}><div className="card-image" style={{ background: item.color }}><img src={item.image} alt={item.title} /><button className="heart-button" onClick={(event) => event.stopPropagation()}>♡</button><span className="session-badge">{item.date}</span></div><div className="card-info"><div className="card-title-row"><h3>{item.title}</h3><span className="rating">★ {item.rating}</span></div><p>{item.subtitle}</p><p className="muted">{item.host} · {item.location}</p><div className="card-footer"><strong><Money value={item.price} /> <small>/ persona</small></strong><span>{item.spots} cupos</span></div></div></article>
}

function Detail({ item, onBack, onAdd, onBook }) {
  const [chosenSession, setChosenSession] = useState(0)
  return <main className="detail-page"><button className="back-button" onClick={onBack}>← Volver a explorar</button><div className="detail-layout"><div><img className="detail-image" src={item.image} alt={item.title} /><div className="detail-thumbs"><img src={item.image} alt="" /><img src={item.image} alt="" /></div></div><div className="detail-copy"><span className="category-label">{item.category}</span><h1>{item.title}</h1><p className="detail-subtitle">{item.subtitle}</p><div className="host-line"><span className="avatar">NF</span><span>Una experiencia de <strong>{item.host}</strong><small> anfitrión verificado</small></span></div><hr /><p>Una tarde para salir de la rutina, conocer rincones únicos y compartir una experiencia pensada para disfrutar sin apuro.</p><div className="session-picker"><div className="session-picker-heading"><strong>Elegí una sesión</strong><span>{sessions.length} fechas disponibles</span></div>{sessions.map((session, index) => <button className={`session-option ${chosenSession === index ? 'selected' : ''}`} key={session.date} onClick={() => setChosenSession(index)}><span className="session-radio">{chosenSession === index ? '✓' : ''}</span><span><strong>{session.date}</strong><small>◷ {session.time}</small></span><em>{session.spots} cupos</em></button>)}</div><div className="detail-price"><strong><Money value={item.price} /></strong><span>por persona · ★ {item.rating}</span></div><button className="primary-button full" onClick={onBook}>Reservar esta sesión <span>→</span></button><button className="outline-button full" onClick={onAdd}>🛒 Agregar al carrito</button><p className="action-hint">Podés revisar y modificar tu reserva antes de confirmar.</p></div></div><section className="reviews-section"><div className="section-heading"><div><p className="eyebrow">LO QUE DICEN</p><h2>Reseñas de esta experiencia</h2></div><strong className="review-score">★ {item.rating} · {reviews.length} reseñas</strong></div><div className="reviews-grid">{reviews.map((review) => <article className="review-item" key={review.name}><div className="review-top"><span className="avatar">{review.name.slice(0, 2).toUpperCase()}</span><span><strong>{review.name}</strong><small>{review.date}</small></span><b>{'★'.repeat(review.rating)}</b></div><p>“{review.text}”</p></article>)}</div></section></main>
}

function Cart({ cart, onBack, onRemove, onCheckout }) {
  const total = cart.reduce((sum, item) => sum + item.price, 0)
  return <main className="inner-page"><button className="back-button" onClick={onBack}>← Seguir explorando</button><div className="page-title"><span className="intro-tag">CHECKOUT SEGURO</span><h1>Tu carrito de<br /><em>experiencias.</em></h1><p>Revisá tus sesiones seleccionadas antes de confirmar.</p></div>{!cart.length ? <Empty title="Tu carrito está vacío" text="Encontrá un plan y reservá tu lugar." action="Explorar experiencias" onClick={onBack} /> : <div className="cart-layout"><div className="cart-list">{cart.map((item) => <article className="cart-item" key={item.id}><img src={item.image} alt={item.title} /><div><span className="category-label">{item.category}</span><h3>{item.title}</h3><p>{item.date}</p><p className="muted">{item.location}</p><button className="remove-button" onClick={() => onRemove(item.id)}>Eliminar</button></div><strong><Money value={item.price} /></strong></article>)}</div><aside className="summary-card"><h2>Resumen del pedido</h2><div><span>Subtotal ({cart.length} sesión)</span><strong><Money value={total} /></strong></div><div><span>Servicio PLAN</span><strong>$0</strong></div><hr /><div className="summary-total"><span>Total</span><strong><Money value={total} /></strong></div><button className="primary-button full" onClick={onCheckout}>Continuar al checkout →</button></aside></div>}</main>
}

function Checkout({ cart, onBack, onSuccess }) {
  const total = cart.reduce((sum, item) => sum + item.price, 0)
  return <main className="inner-page narrow"><button className="back-button" onClick={onBack}>← Volver al carrito</button><div className="page-title"><span className="intro-tag">PASO 2 DE 2</span><h1>Confirmá tu<br /><em>experiencia.</em></h1><p>Completá tus datos para asegurar tus lugares.</p></div><div className="checkout-layout"><div className="form-card"><h2>Datos de contacto</h2><label>Nombre completo<input placeholder="Sofía Rubachin" /></label><label>Email<input placeholder="sofia@email.com" type="email" /></label><label>Código de descuento<input placeholder="PLANFINDE10" /></label><div className="notice">♧ Tus datos están protegidos y no guardamos información de pago.</div></div><aside className="summary-card"><h2>Tu reserva</h2>{cart.map((item) => <div className="mini-item" key={item.id}><img src={item.image} alt="" /><span>{item.title}<small>{item.date}</small></span><strong><Money value={item.price} /></strong></div>)}<hr /><div className="summary-total"><span>Total a pagar</span><strong><Money value={total} /></strong></div><button className="primary-button full" onClick={onSuccess}>Confirmar reserva ✦</button></aside></div></main>
}

function Confirmation({ onNavigate }) { return <main className="success-page"><div className="success-icon">✓</div><span className="intro-tag">RESERVA CONFIRMADA</span><h1>Tu plan ya<br /><em>es real.</em></h1><p>Te enviamos todos los detalles a tu email. Mostrá este voucher al anfitrión.</p><div className="voucher"><small>VOUCHER DE EXPERIENCIA</small><strong>ETRIP-8K4M2P</strong><span>Guardalo, lo vas a necesitar al llegar.</span></div><button className="primary-button" onClick={() => onNavigate('bookings')}>Ver mis reservas →</button></main> }
function Bookings({ onNavigate }) { return <main className="inner-page"><div className="page-title"><span className="intro-tag">MI ACTIVIDAD</span><h1>Mis <em>reservas.</em></h1><p>Todos tus próximos planes en un solo lugar.</p></div><div className="booking-card"><img src={experiences[0].image} alt="" /><div><span className="category-label">PRÓXIMA EXPERIENCIA</span><h2>{experiences[0].title}</h2><p>◷ {experiences[0].date}</p><p>⌖ {experiences[0].location}</p></div><div className="voucher-code">ETRIP-8K4M2P<small>Voucher confirmado</small></div></div><Empty title="No tenés más reservas" text="Guardá tus próximos planes acá." action="Explorar" onClick={() => onNavigate('home')} /></main> }
function Orders({ onNavigate, onDetail }) { return <main className="inner-page"><div className="page-title"><span className="intro-tag">HISTORIAL</span><h1>Mis <em>órdenes.</em></h1><p>Consultá tus compras y comprobantes.</p></div><button className="table-card order-row" onClick={onDetail}><div><span>#ETRIP-1042</span><strong>Compra de experiencias</strong><small>26 de septiembre de 2025 · 1 reserva</small></div><b className="status">Confirmada</b><strong>$28.000</strong><span className="order-arrow">→</span></button><Empty title="Eso es todo por ahora" text="Tus próximas compras van a aparecer acá." action="Explorar planes" onClick={() => onNavigate('home')} /></main> }

function OrderDetail({ onBack }) { return <main className="inner-page"><button className="back-button" onClick={onBack}>← Volver a mis órdenes</button><div className="page-title"><span className="intro-tag">ORDEN CONFIRMADA</span><h1>Detalle de<br /><em>tu compra.</em></h1><p>Orden #ETRIP-1042 · 26 de septiembre de 2025</p></div><div className="order-detail-layout"><section className="order-panel"><div className="order-status"><span>✓</span><div><strong>Compra confirmada</strong><small>Tu voucher ya está disponible</small></div><b>Confirmada</b></div><div className="order-experience"><img src={experiences[0].image} alt={experiences[0].title} /><div><span className="category-label">{experiences[0].category}</span><h2>{experiences[0].title}</h2><p>{experiences[0].subtitle}</p><p>◷ {experiences[0].date}</p><p>⌖ {experiences[0].location}</p></div></div><div className="voucher-large"><small>CÓDIGO DE VOUCHER</small><strong>ETRIP-8K4M2P</strong><p>Presentá este código al anfitrión al comenzar la experiencia.</p></div></section><aside className="summary-card"><h2>Resumen de pago</h2><div><span>1 lugar</span><strong>$28.000</strong></div><div><span>Servicio PLAN</span><strong>$0</strong></div><hr /><div className="summary-total"><span>Total pagado</span><strong>$28.000</strong></div><button className="outline-button full" onClick={() => window.print()}>Descargar comprobante</button></aside></div></main> }
function Reviews({ onNotify }) { return <main className="inner-page"><div className="page-title"><span className="intro-tag">TU VOZ</span><h1>Mis <em>reseñas.</em></h1><p>Compartí lo que viviste y ayudá a otros a elegir.</p></div><div className="review-card"><div className="stars">★★★★★</div><h2>Paseo por La Boca</h2><p>“Una experiencia hermosa, Nico y Sofi nos hicieron descubrir lugares increíbles.”</p><small>Publicada hace 2 semanas</small><button onClick={() => onNotify('La reseña se puede editar desde el detalle')}>Editar reseña</button></div></main> }
function Profile({ onNavigate }) { return <main className="inner-page"><div className="profile-hero"><span className="big-avatar">SR</span><div><span className="intro-tag">CLIENTE</span><h1>Sofía Rubachin</h1><p>Buenos Aires · Se unió en 2025</p></div><button className="outline-button" onClick={() => onNavigate('host')}>Modo anfitrión</button></div><div className="stats"><div><strong>4</strong><span>reservas</span></div><div><strong>1</strong><span>reseña</span></div><div><strong>0</strong><span>experiencias</span></div></div><div className="empty-panel"><h2>Tu perfil público</h2><p>Cuando publiques una experiencia, va a aparecer acá.</p></div></main> }
function Host({ onNotify }) { return <main className="inner-page"><div className="page-title"><span className="intro-tag">MODO ANFITRIÓN</span><h1>Creá algo que<br /><em>la gente recuerde.</em></h1><p>Publicá tu experiencia, organizá sesiones y conectá con personas.</p></div><div className="host-actions"><button className="host-action" onClick={() => onNotify('Formulario de nueva experiencia próximamente')}><span>＋</span><strong>Crear experiencia</strong><small>Fotos, descripción y categoría</small></button><button className="host-action"><span>◷</span><strong>Gestionar sesiones</strong><small>Organizá tus próximos turnos</small></button><button className="host-action"><span>♧</span><strong>Ver reservas</strong><small>Revisá quién viene</small></button></div><h2 className="subheading">Mis experiencias (1)</h2><ExperienceCard item={experiences[0]} onSelect={() => onNotify('Editor de experiencia próximamente')} /></main> }
function Admin() { return <main className="inner-page"><div className="page-title"><span className="intro-tag">ADMINISTRACIÓN</span><h1>Panel de<br /><em>control.</em></h1><p>Gestioná la actividad global de PLAN.</p></div><div className="admin-grid"><div><strong>1.248</strong><span>usuarios registrados</span></div><div><strong>86</strong><span>experiencias activas</span></div><div><strong>324</strong><span>reservas este mes</span></div><div><strong>$4.2M</strong><span>ventas acumuladas</span></div></div><div className="admin-links"><button>♙ Gestionar usuarios <span>→</span></button><button>▦ Gestionar categorías <span>→</span></button><button>♧ Gestionar cupones <span>→</span></button><button>◷ Ver todas las órdenes <span>→</span></button></div></main> }
function Auth({ mode, onClose, onSuccess }) { const [login, setLogin] = useState(mode === 'login'); return <div className="modal-backdrop" onClick={onClose}><div className="auth-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><div className="brand modal-brand">PLAN<span>✦</span></div><h2>{login ? 'Qué bueno verte.' : 'Empezá tu próximo plan.'}</h2><p>{login ? 'Ingresá para continuar con tus reservas.' : 'Creá tu cuenta y descubrí nuevas experiencias.'}</p>{!login && <input placeholder="Nombre completo" />}{<input placeholder="Email" type="email" />}<input placeholder="Contraseña" type="password" /><button className="primary-button full" onClick={onSuccess}>{login ? 'Iniciar sesión' : 'Crear cuenta'} →</button><button className="switch-auth" onClick={() => setLogin(!login)}>{login ? '¿No tenés cuenta? Registrate' : 'Ya tengo una cuenta'}</button></div></div> }
function Empty({ title, text, action, onClick }) { return <div className="empty-state"><div>✦</div><h2>{title}</h2><p>{text}</p>{action && <button className="primary-button" onClick={onClick}>{action} →</button>}</div> }

export { Home, Detail, Cart, Checkout, Confirmation, Bookings, Orders, OrderDetail, Reviews, Profile, Host, Admin, Auth }
